on: [push]

jobs:
  authelia-action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authelia action
        id: authelia
        uses: bubylou/authelia-action@v1
